name: CI/CD Pipeline for JCR

on: 
  push:
    branches: ["rental_package_jack"]
  pull_request:
    branches: ["rental_package_jack"]

permissions:
  contents: read
  packages: write

jobs:
  build_test: 

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set Up JDK 25
      uses: actions/setup-java@v3
      with:
        java-version: '25-ea'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file code/pom.xml


  publish:
    runs-on: ubuntu-latest
    needs: build_test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '25-ea'
          distribution: 'temurin'
      - name: Publish to GitHub Packages
        run: mvn deploy --settings .github/maven-settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          

    
  
    
